### ISSUE TITLE
Take photo with camera does not work

### ISSUE THREAD

**Issue by monicakCS** [Team2-lyfestyle/lyfestyle#22]
The messages I got were.
" Possible unhandled promise rejection. Error: Missing camera or camera roll permission"

Upload from cameral roll works

**Comment by YoshidaLeo** [comment]
Fixed the issue. Someone with IOS please test @monicakCS

**Comment by monicakCS** [comment]
Testing right now.

**Comment by monicakCS** [comment]
@YoshidaLeo still getting the same error.
